2019-01-28 15:31:33,731 ERROR: Exception on / [GET] [in /Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/flatironschool/Development/code/flask/flask_blog/app/routes.py", line 40, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/flatironschool/Development/code/flask/flask_blog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/flatironschool/Development/code/flask/flask_blog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap' %}
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap
2019-01-28 15:33:26,553 INFO: Blog startup [in /Users/flatironschool/Development/code/flask/flask_blog/app/__init__.py:53]
2019-01-28 16:39:08,709 INFO: Blog startup [in /Users/flatironschool/Development/code/flask/flask_blog/app/__init__.py:70]
2019-01-28 16:39:16,844 ERROR: Exception on /index [GET] [in /Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/flatironschool/Development/code/flask/flask_blog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/flatironschool/Development/code/flask/flask_blog/app/main/routes.py", line 33, in index
    page, app.config['POSTS_PER_PAGE'], False)
NameError: name 'app' is not defined
